version: '2.1'
services:
  main:
    environment:
      USERNAME: "${USERNAME:?run only with a ./start.sh. because variables are defined there.}"
      UID: "${xUID:?run only with a ./start.sh. because variables are defined there.}"
      GID: "${xGID:?run only with a ./start.sh. because variables are defined there.}"
      GID_DOCKER: "${xGID_DOCKER:?run only with a ./start.sh. because variables are defined there.}"
      SSH_AUTH_SOCK: /ssh-agent
      PATH: "$MY_PATH/../bin:$MY_PATH/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$MY_HOMEPATH/.local/bin"
      WORKDIR: "$MY_PATH/../"
      EDITOR: nano
    build:
      context: .
    cap_add:
      - IPC_LOCK
    volumes:
    - "~:$MY_HOMEPATH"
    - "$SSH_AUTH_SOCK:/ssh-agent"
    - "/mnt:/mnt"
    - "/etc/hosts:/etc/hosts"
    - "/home/$USERNAME/.bash_history:/home/$USERNAME/.bash_history"
    - "/var/run/docker.sock:/var/run/docker.sock"
    container_name: "${CONTAINER_NAME:?run only with a ./start.sh. because variables are defined there.}"
    
